name: Java CI with Gradle

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [11, 16]
      fail-fast: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v2.1.0
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}
      - name: Cache gradle
        uses: actions/cache@v2.1.6
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-
      - name: Configure git
        run: |
          git config --global user.email "no-reply@github.com"
          git config --global user.name "Github Actions"
      - name: Download Velocity
        run: "wget https://versions.velocitypowered.com/download/3.0.0.jar -O libs"
      - name: Build pligins
        run: ./gradlew build
      - name: Upload a build artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: LimboAPI Built On ${{ matrix.java }} JDK
          path: "*/build/libs/*-all.jar"
